### ISSUE TITLE
FYI: Error on SortedCreatedAssets Script

### ISSUE THREAD

**Issue by iiidefektiii** [Badgerdox/AddressableAsset-HowTo#1]
Assets\Scripts\Addressables_Samples\SortedCreatedAssets.cs(13,28): error CS1503: Argument 1: cannot convert from 'string[]' to 'System.Collections.Generic.List<string>'

**Comment by Badgerdox** [comment]
Try changing your array to a list

**Comment by iiidefektiii** [comment]
I did. In case someone else who doesn't comes accross the error.
